pipeline {
    agent any
    stages {
        stage('Init') {
            steps {
                cleanWs()
            }
        }
        stage('Checkout') {
            steps {
                git branch: 'main',
                        url: 'https://github.com/svillarreal/ticketevolution.git'
            }
        }
        stage('Build and push docker image') {
            steps {
                sh 'cd backend-java && docker buildx build --platform linux/amd64,linux/arm64 -t shiryuknight/ticketevolution-be:v1.0.10 --push .'
            }
        }
    }
}