pipeline {
    agent any
    environment {
        DOCKERHUB_CREDENTIALS = credentials('DockerHub')
    }
    stages {
        stage('Init') {
            steps {
                cleanWs()
            }
        }
        stage('Checkout') {
            steps {
                git branch: 'main',
                        url: 'https://github.com/svillarreal/ticketevolution.git'
            }
        }
        stage('Docker Login') {
            steps {
                sh ' echo $DOCKERHUB_CREDENTIALS_PWD | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin '
            }
        }
        stage('Build and push docker image') {
            steps {
                sh '''
                    cd backend-java
                    docker buildx build --platform linux/amd64,linux/arm64 -t shiryuknight/ticketevolution-be:v1.0.10 --push .
                '''
            }
        }
    }
}
